<a href="https://colab.research.google.com/github/siliconemonster/AD-TrabalhoFinal/blob/main/Simula%C3%A7%C3%A3o_AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando bibliotecas

In [1]:
import random
from random import sample
from random import random
from matplotlib import pyplot as plt
from matplotlib.legend_handler import HandlerLine2D
from collections import Counter
import sympy as sy
from numpy.linalg import matrix_power
from fractions import Fraction
import math
from math import *
import numpy as np
from numpy import random
import pandas as pd
import queue 
from scipy.stats import poisson

<h2> I. Simulação

In [2]:
def initializeCache():  
  cache = sample([1,2,3], k= 2)
  return cache

In [3]:
def cacheReceivesReq(caso, cache, requisicao):
  RequicaoAtendida = 0
  #print("Conteudo Requisicao: " + str(requisicao))
  #print("Cache:" + str(cache))

  if (requisicao in cache):
    if(caso == "FIFO" or caso == "Random" or caso == "Estatica"):
      cache = cache
      RequicaoAtendida = 1    
      #print("Cache possui requisção!") 

    elif (caso == "LRU"):
      RequicaoAtendida = 1    
      #print("Cache possui requisição!")

      cache.remove(requisicao)
      cache.insert(0, requisicao)
      #print("Novo estado da cache: " + str(cache)) 
   
  else:
    if (caso == "FIFO" or caso == "LRU"):
      cache.insert(0, requisicao)
      del cache[-1]
      #print("Novo estado da cache: " + str(cache)) 

    elif (caso == "Random"):
      cache.insert(0, requisicao)
      del cache[random.randint(-2,0)]
      #print("Novo estado da cache: " + str(cache)) 

  return cache, RequicaoAtendida

In [4]:
def simulacaoCenario1(tipo, trials): 
    
  mediaSucessos = []

  for i in range(trials):

    queueCache1 = {}
    queueCache2 = {}

    sucesso = 0
    mediaSucesso = 0  

    cache1 = initializeCache()
    cache2 = initializeCache()

    reqAtendidasC1 = []
    reqAtendidasC2 = []


    t = 0
    max = 1000
    while (t < max):

      RequicaoAtendida = 0
      requisicao = random.randint(1,4)

      #print("Conteudo Requisitado: " + str(requisicao))
      #print("Cache 1: " + str(cache1))
      #print("Cache 2: " + str(cache2))


      TempoC1 = np.random.poisson(1/3,1)
      requisicaoTempoC1 = t + TempoC1[0]
      TempoC2 = np.random.poisson(1/3,1)
      requisicaoTempoC2 = t + TempoC2[0]      


      # Inserindo a requisição na fila
      queueCache1["req" + str(t)] = [requisicaoTempoC1,requisicao]
      queueCache2["req" + str(t)] = [requisicaoTempoC2,requisicao]
      
      # OrdenandO a Fila
      queueCache1 = {k: v for k, v in sorted(queueCache1.items(), key=lambda item: item[1])}
      queueCache2 = {k: v for k, v in sorted(queueCache2.items(), key=lambda item: item[1])}

      #print("Fila cache 1:" + str(queueCache1))
      #print("Fila cache 2:" + str(queueCache2))

      while (1):

        if (len(queueCache1)>0):
          primRequisicao = list(queueCache1.keys())[0]
          requisicao = queueCache1[primRequisicao]
          conteudoReq = requisicao[1]          
          tempoReeq = requisicao[0]

          if (tempoReeq == t):
            del queueCache1[primRequisicao]
            #print(str(primRequisicao) + " vai para a cache 1")
            cache1, RequicaoAtendida = cacheReceivesReq(tipo, cache1, conteudoReq)
            if (RequicaoAtendida):
              reqAtendidasC1.append(primRequisicao)
              #print("Requisição atendida")
            #else:
              #print("Requisição não atendida")


          else: break

        else: break

      while (1):

        if(len(queueCache2)>0):

          primRequisicao = list(queueCache2.keys())[0]
          requisicao = queueCache2[primRequisicao]
          conteudoReq = requisicao[1]
          tempoReeq = requisicao[0]

          if (tempoReeq == t):
            del queueCache2[primRequisicao]
            #print(str(primRequisicao) + " vai para a cache 2")
            cache2, RequicaoAtendida = cacheReceivesReq(tipo, cache2, conteudoReq)
            if (RequicaoAtendida):
              reqAtendidasC2.append(primRequisicao)
              #print("Requisição atendida")
            #else:
              #print("Requisição não atendida")

          else: break
        
        else: break

      #if(RequicaoAtendida):
          #print("Sucesso!")

      t = t + 1

      
    #print(reqAtendidasC1)
    #print(reqAtendidasC2)
    reqAtendidas = list(set(reqAtendidasC1).union(set(reqAtendidasC2)))
    #print(reqAtendidas)
    sucessos = len(reqAtendidas)
    #print("Sucessos = " + str(sucessos))
    mediaSucessos.append(sucessos/t)
    
  
  print("Media Sucessos = " + str(mediaSucessos))

    
  return mediaSucessos


In [5]:
simulacaoCenario1("LRU", 3)

Media Sucessos = [0.738, 0.736, 0.705]


[0.738, 0.736, 0.705]

In [6]:
random.seed(8)
tipo = "FIFO"

queueCache1 = {}
queueCache2 = {}

sucesso = 0
mediaSucesso = 0  

cache1 = initializeCache()
cache2 = initializeCache()
t = 0
max = 10
while (t < max):

  RequicaoAtendida = 0
  requisicao = random.randint(1,4)

  print("Conteudo Requisitado: " + str(requisicao))
  print("Cache 1: " + str(cache1))
  print("Cache 2: " + str(cache2))


  TempoC1 = np.random.poisson(1/3,1)
  requisicaoTempoC1 = t + TempoC1[0]
  TempoC2 = np.random.poisson(1/3,1)
  requisicaoTempoC2 = t + TempoC2[0]      


  # Inserindo a requisição na fila
  queueCache1["req" + str(t)] = [requisicaoTempoC1,requisicao]
  queueCache2["req" + str(t)] = [requisicaoTempoC2,requisicao]
  
  # OrdenandO a Fila
  queueCache1 = {k: v for k, v in sorted(queueCache1.items(), key=lambda item: item[1])}
  queueCache2 = {k: v for k, v in sorted(queueCache2.items(), key=lambda item: item[1])}

  print("Fila cache 1:" + str(queueCache1))
  print("Fila cache 2:" + str(queueCache2))

  while (1):

    if (len(queueCache1)>0):
      primRequisicao = list(queueCache1.keys())[0]
      requisicao = queueCache1[primRequisicao]
      conteudoReq = requisicao[1]
      tempoReeq = requisicao[0]

      if (tempoReeq == t):
        del queueCache1[primRequisicao]
        print(str(primRequisicao) + " vai para a cache 1")
        cache1, RequicaoAtendida = cacheReceivesReq(tipo, cache1, conteudoReq)
        if (RequicaoAtendida):
          print("Requisição atendida")
        else:
          print("Requisição não atendida")


      else: break

    else: break

  while (1):

    if(len(queueCache2)>0):

      primRequisicao = list(queueCache2.keys())[0]
      requisicao = queueCache2[primRequisicao]
      conteudoReq = requisicao[1]
      tempoReeq = requisicao[0]

      if (tempoReeq == t):
        del queueCache2[primRequisicao]
        print(str(primRequisicao) + " vai para a cache 2")
        cache2, RequicaoAtendida = cacheReceivesReq(tipo, cache2, conteudoReq)
        if (RequicaoAtendida):
          print("Requisição atendida")
        else:
          print("Requisição não atendida")

      else: break
    
    else: break

  if(RequicaoAtendida):
      print("Sucesso!")
      sucesso = sucesso + 1  

  t = t + 1
  print("")

Conteudo Requisitado: 1
Cache 1: [1, 3]
Cache 2: [3, 2]
Fila cache 1:{'req0': [2, 1]}
Fila cache 2:{'req0': [0, 1]}
req0 vai para a cache 2
Requisição não atendida

Conteudo Requisitado: 1
Cache 1: [1, 3]
Cache 2: [1, 3]
Fila cache 1:{'req1': [1, 1], 'req0': [2, 1]}
Fila cache 2:{'req1': [2, 1]}
req1 vai para a cache 1
Requisição atendida
Sucesso!

Conteudo Requisitado: 1
Cache 1: [1, 3]
Cache 2: [1, 3]
Fila cache 1:{'req0': [2, 1], 'req2': [3, 1]}
Fila cache 2:{'req1': [2, 1], 'req2': [2, 1]}
req0 vai para a cache 1
Requisição atendida
req1 vai para a cache 2
Requisição atendida
req2 vai para a cache 2
Requisição atendida
Sucesso!

Conteudo Requisitado: 3
Cache 1: [1, 3]
Cache 2: [1, 3]
Fila cache 1:{'req2': [3, 1], 'req3': [4, 3]}
Fila cache 2:{'req3': [3, 3]}
req2 vai para a cache 1
Requisição atendida
req3 vai para a cache 2
Requisição atendida
Sucesso!

Conteudo Requisitado: 1
Cache 1: [1, 3]
Cache 2: [1, 3]
Fila cache 1:{'req3': [4, 3], 'req4': [5, 1]}
Fila cache 2:{'req4': [4, 1

In [7]:
len(queueCache1)


0

In [8]:
primRequisicao[1]

'e'

In [9]:
def simulacaoCenario2(tipo, trials):
  queueCache1 = {}
  queueCache2 = {}
  sucesso = 0
  mediaSucesso = 0  
  cache1 = initializeCache()
  cache2 = initializeCache()
  usermiss = 0

  
  for i in range (trials):
    RequicaoAtendida = 0

    canal1 = random.rand()
    canal1falhou = 1
    sucessoc1 = 0
    requisicao = random.randint(1,4) 

    #print("\n Requisição: " + str(requisicao))
    #print("Cache 1: " + str(cache1))
    #print("Cache 2: " + str(cache2))

    if(canal1 <= 0.9):
      cache1, RequicaoAtendida = cacheReceivesReq(tipo, cache1, requisicao)
    #else:
     # print("Canal Falhou")

    canal2 = random.rand()
    if(canal2 <= 0.9):        
      cache2, RequicaoAtendida = cacheReceivesReq(tipo, cache2, requisicao)
    #else:
     # print("Canal Falhou")

    if(RequicaoAtendida):
      sucesso = sucesso + 1

    else:
      usermiss = usermiss + 1
  print("Media Sucessos = " + str(sucesso/trials)) 
  print("Usermiss = " + str(usermiss))
  print("Media Usermiss = " + str(usermiss/trials))

In [ ]:
simulacaoCenario1("FIFO", 100000)

In [ ]:
simulacaoCenario1("LRU", 100000)

In [ ]:
simulacaoCenario1("Random", 100000)

In [ ]:
simulacaoCenario2("FIFO", 100000)

In [ ]:
'''
casoFifoMarkov  = [[sy.Rational('2/3'), 0, 0, 0,sy.Rational('1/3'),0], 
    [0, sy.Rational('2/3'), sy.Rational('1/3'), 0,0,0],
    [0, 0, sy.Rational('2/3'), 0,0,sy.Rational('1/3')],
    [sy.Rational('1/3'), 0, sy.Rational('2/3'), 0,0,0],
    [0, 0, 0, sy.Rational('1/3'),sy.Rational('2/3'),0],
    [0, sy.Rational('1/3'), 0, 0,0,sy.Rational('2/3')]] '''

In [ ]:
matrix_power(markovCasoFIFO, 10000).round(decimals=2)

array([[0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33],
       [0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33]])

In [ ]:
matrix_power(markovCasoLRU, 10000).round(decimals=2)

array([[0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17]])

In [ ]:
matrix_power(markovCasoRandom, 10000).round(decimals=2)

array([[0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33]])

In [ ]:
qCache1 = {}

In [ ]:
qCache1 = 

<h2> II. Parte Analítica

<h3> Cenário 1

Aqui calcularemos a probabilidade de sucesso utilizando cadeias de Markov para comprovar analíticamente o que fizemos na simulação.

In [12]:
# declaração das matrizes de transição - uma única cache

#FIFO - Estados são: AB, AC, BA, BC, CA e CB
markovCasoFIFO = np.array([[2/3, 0, 0, 0,1/3,0], 
                           [0, 2/3, 1/3, 0,0,0],
                           [0, 0, 2/3, 0,0,1/3],
                           [1/3, 0,0,2/3,0,0],
                           [0, 0, 0, 1/3,2/3,0],
                           [0, 1/3, 0, 0,0,2/3]])

#LRU - Estados são: AB, AC, BA, BC, CA e CB
markovCasoLRU  = np.array([[1/3, 0, 1/3, 0,1/3,0], 
                           [0, 1/3, 1/3, 0,1/3,0],
                           [1/3, 0, 1/3, 0,0,1/3],
                           [1/3, 0,0,1/3,0,1/3],
                           [0, 1/3, 0, 1/3,1/3,0],
                           [0, 1/3, 0, 1/3,0,1/3]])

#RANDOM - Estados são: AB, AC e BC
markovCasoRandom = np.array([[2/3, 1/6, 1/6], 
                             [1/6, 2/3, 1/6],
                             [1/6, 1/6, 2/3]])

# declaração das probabilidades de sair cada tipo de requisção
prob = [["A",1/3], ["B",1/3], ["C",1/3]]
estados = [["AB"], ["AC"], ["BA"], ["BC"], ["CA"], ["CB"]]

In [13]:
# Função para calcular a distribuição estacionária de uma cadeia de Markov por meio de uma matriz de transição P
def dist_estacionaria(P):
  evals, evecs = np.linalg.eig(P.T) #We have to transpose so that Markov transitions correspond to right multiplying by a column vector.  np.linalg.eig finds right eigenvectors.
  evec1 = evecs[:,np.isclose(evals, 1)]
  evec1 = evec1[:,0]
  stationary = evec1 / evec1.sum()
  stationary = stationary.real # parte real (acha autovalores e autovetores complexos)

  print(stationary)
  return stationary

In [14]:
# Função para transformar a distribuição estacionária em uma tupla
def forma_tupla(P):
  estacionaria_nomes = estados
  estacionaria_valores = dist_estacionaria(P)

  for i in range (len(estacionaria_valores)):
    estacionaria_nomes[i].append(estacionaria_valores[i])

  return estacionaria_nomes

In [44]:
# Função para calcular a probabilidade de sucesso em uma única cache
def calcula_sucesso(P):
  estacionaria = forma_tupla(P)
  sucesso = 0
  for i in range(len(prob)):
    for j in range(len(estacionaria)):
      
      if (prob[i][0] in estacionaria[j][0]):
        #print("\nPi_" + str(estacionaria[j][0])+" * P(" + str(prob[i][0]) + ")")
        #print(str(estacionaria[j][1])+" * " + str(prob[i][1]))
        sucesso = sucesso + (prob[i][1]*estacionaria[j][1])
        #print("Sucesso: " + str(sucesso))
  
  return sucesso

In [62]:
# Função para calcular sucesso em ambas as caches 
def sucesso_total(P):
  sucesso = 0
  falha_uma = 0
  sucesso_uma = calcula_sucesso(P)
  falha_uma = 1 - sucesso_uma

  # Stot = S*S + S*F (OU A ORDEM IMPORTA??? 2*S*F???)
  sucesso = sucesso_uma * sucesso_uma + 2 * sucesso_uma * falha_uma
  falha = 1 - sucesso

  return sucesso

sucesso_total(markovCasoFIFO)

[0.33333333 0.         0.         0.33333333 0.33333333 0.        ]


0.8888888888888888

In [63]:
# Função para calcular a probabilidade de falha em uma única cache
def calcula_falha(P):
  estacionaria = forma_tupla(P)
  falha = 0
  for i in range(len(prob)):
    for j in range(len(estacionaria)):
      
      if (prob[i][0] not in estacionaria[j][0]):
        #print("\nPi_" + str(estacionaria[j][0])+" * P(" + str(prob[i][0]) + ")")
        #print(str(estacionaria[j][1])+" * " + str(prob[i][1]))
        falha = falha + (prob[i][1]*estacionaria[j][1])
        #print("Falha: " + str(sucesso))
  
  return falha

In [64]:
# Função para calcular falha em ambas as caches 
def falha_total(P):
  sucesso_uma = 0
  falha = 0
  falha_uma = calcula_falha(P)
  sucesso_uma = 1 - falha_uma

  # Ftot = F*F
  falha = falha_uma * falha_uma
  sucesso = 1 - falha
  print(sucesso)

  return falha

falha_total(markovCasoFIFO)

[0.33333333 0.         0.         0.33333333 0.33333333 0.        ]
0.8888888888888888


0.1111111111111111