<a href="https://colab.research.google.com/github/siliconemonster/AD-TrabalhoFinal/blob/main/Simula%C3%A7%C3%A3o_AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importando bibliotecas

In [ ]:
import random
from random import sample
from random import random
from matplotlib import pyplot as plt
from matplotlib.legend_handler import HandlerLine2D
from collections import Counter
import sympy as sy
from numpy.linalg import matrix_power
from fractions import Fraction
import math
from math import *
import numpy as np
from numpy import random
import pandas as pd
import queue 

In [ ]:
def initializeCache():  
  cache = sample([1,2,3], k= 2)
  return cache

In [ ]:
def cacheReceivesReq(caso, cache, requisicao):
  RequicaoAtendida = 0

  if (requisicao in cache):
    if(caso == "FIFO" or caso == "Random" or caso == "Estatica"):
      cache = cache
      RequicaoAtendida = 1    
      #print("Cache possui requisção!") 

    elif(caso == "LRU"):
      RequicaoAtendida = 1    
      #print("Cache possui requisição!")

      cache.remove(requisicao)
      cache.insert(0, requisicao)
      #print("Novo estado da cache: " + str(cache)) 
   
  else:
    if(caso == "FIFO" or caso == "LRU"):
      cache.insert(0, requisicao)
      del cache[-1]
      #print("Novo estado da cache: " + str(cache)) 

    elif(caso == "Random"):
      cache.insert(0, requisicao)
      del cache[random.randint(-2,0)]
      #print("Novo estado da cache: " + str(cache)) 

  return cache, RequicaoAtendida

In [ ]:
def simulacaoCenario1(tipo, trials):
  queueCache1 = []
  queueCache2 = []
  sucesso = 0
  mediaSucesso = 0  
  cache1 = initializeCache()
  cache2 = initializeCache()
  cache3 = initializeCache()
  print("Cache 1: " + str(cache1))
  print("Cache 2: " + str(cache2))
  print("Cache 3: " + str(cache3))

  
  for i in range (trials):
    RequicaoAtendida = 0
    requisicao = random.randint(1,4)
    #print("Requisição: " + str(requisicao))
    #print("Cache 1: " + str(cache1))
    #print("Cache 2: " + str(cache2))

    cache1, RequicaoAtendida = cacheReceivesReq(tipo, cache1, requisicao)
    cache2, RequicaoAtendida = cacheReceivesReq(tipo, cache2, requisicao)
    cache3, RequicaoAtendida = cacheReceivesReq(tipo, cache3, requisicao)

    if(RequicaoAtendida):
      sucesso = sucesso + 1
      #print("Sucesso")

  mediaSucesso = sucesso/trials 
  print("Media Sucessos = " + str(mediaSucesso))
  return mediaSucesso

In [ ]:
def simulacaoCenario2(tipo, trials):
  queueCache1 = []
  queueCache2 = []
  sucesso = 0
  mediaSucesso = 0  
  cache1 = initializeCache()
  cache2 = initializeCache()
  usermiss = 0

  
  for i in range (trials):
    RequicaoAtendida = 0

    canal1 = random.rand()
    canal1falhou = 1
    sucessoc1 = 0
    requisicao = random.randint(1,4) 

    #print("\n Requisição: " + str(requisicao))
    #print("Cache 1: " + str(cache1))
    #print("Cache 2: " + str(cache2))

    if(canal1 <= 0.9):
      cache1, RequicaoAtendida = cacheReceivesReq(tipo, cache1, requisicao)
    #else:
     # print("Canal Falhou")

    canal2 = random.rand()
    if(canal2 <= 0.9):        
      cache2, RequicaoAtendida = cacheReceivesReq(tipo, cache2, requisicao)
    #else:
     # print("Canal Falhou")

    if(RequicaoAtendida):
      sucesso = sucesso + 1

    else:
      usermiss = usermiss + 1
  print("Media Sucessos = " + str(sucesso/trials)) 
  print("Usermiss = " + str(usermiss))
  print("Media Usermiss = " + str(usermiss/trials))

In [ ]:
simulacaoCenario1("FIFO", 100000)

Cache 1: [2, 1]
Cache 2: [3, 2]
Cache 3: [3, 1]
Media Sucessos = 0.66566


0.66566

In [ ]:
simulacaoCenario1("LRU", 100000)

Media Sucessos = 0.66668


0.66668

In [ ]:
simulacaoCenario1("Random", 100000)

Media Sucessos = 0.66685


0.66685

In [ ]:
simulacaoCenario2("FIFO", 100000)

Media Sucessos = 0.66128
Usermiss = 33872
Media Usermiss = 0.33872


In [ ]:
'''
casoFifoMarkov  = [[sy.Rational('2/3'), 0, 0, 0,sy.Rational('1/3'),0], 
    [0, sy.Rational('2/3'), sy.Rational('1/3'), 0,0,0],
    [0, 0, sy.Rational('2/3'), 0,0,sy.Rational('1/3')],
    [sy.Rational('1/3'), 0, sy.Rational('2/3'), 0,0,0],
    [0, 0, 0, sy.Rational('1/3'),sy.Rational('2/3'),0],
    [0, sy.Rational('1/3'), 0, 0,0,sy.Rational('2/3')]] '''

"\ncasoFifoMarkov  = [[sy.Rational('2/3'), 0, 0, 0,sy.Rational('1/3'),0], \n    [0, sy.Rational('2/3'), sy.Rational('1/3'), 0,0,0],\n    [0, 0, sy.Rational('2/3'), 0,0,sy.Rational('1/3')],\n    [sy.Rational('1/3'), 0, sy.Rational('2/3'), 0,0,0],\n    [0, 0, 0, sy.Rational('1/3'),sy.Rational('2/3'),0],\n    [0, sy.Rational('1/3'), 0, 0,0,sy.Rational('2/3')]] "

In [ ]:
markovCasoFIFO  = [[2/3, 0, 0, 0,1/3,0], 
    [0, 2/3, 1/3, 0,0,0],
    [0, 0, 2/3, 0,0,1/3],
    [1/3, 0,0,2/3,0,0],
    [0, 0, 0, 1/3,2/3,0],
    [0, 1/3, 0, 0,0,2/3]]

markovCasoLRU  = [[1/3, 0, 1/3, 0,1/3,0], 
    [0, 1/3, 1/3, 0,1/3,0],
    [1/3, 0, 1/3, 0,0,1/3],
    [1/3, 0,0,1/3,0,1/3],
    [0, 1/3, 0, 1/3,1/3,0],
    [0, 1/3, 0, 1/3,0,1/3]]

markovCasoRandom = [[2/3, 1/6, 1/6], 
    [1/6, 2/3, 1/6],
    [1/6, 1/6, 2/3]]

In [ ]:
matrix_power(markovCasoFIFO, 10000).round(decimals=2)

array([[0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33],
       [0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.33, 0.  , 0.  , 0.33, 0.33, 0.  ],
       [0.  , 0.33, 0.33, 0.  , 0.  , 0.33]])

In [ ]:
matrix_power(markovCasoLRU, 10000).round(decimals=2)

array([[0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17],
       [0.17, 0.17, 0.17, 0.17, 0.17, 0.17]])

In [ ]:
matrix_power(markovCasoRandom, 10000).round(decimals=2)

array([[0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33]])